import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    // routeTree.gen.ts is generated by @tanstack/router-plugin and committed so that
    // `tsc --noEmit` passes in CI without a prior build. api-schema.d.ts is generated
    // by openapi-typescript.
    ignores: ['dist', 'coverage', 'src/routeTree.gen.ts', 'src/lib/api-schema.d.ts'],
  },

  js.configs.recommended,

  // Type-aware linting, scoped to TypeScript. This is the reason TypeScript is pinned to
  // 6.0.3 rather than 7.x: typescript-eslint@8.64.0 peer-caps at `typescript <6.1.0`, and
  // TS 7 would silently disable every rule below.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      ...tseslint.configs.recommendedTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
      // eslint-plugin-react-hooks@7 ships the React Compiler rules (purity, immutability,
      // refs, set-state-in-effect/render). They matter: the compiler bails out *silently*
      // on rule-breaking components, and this is how you find out that it bailed.
      // Note `configs.recommended` is still the legacy eslintrc shape, which ESLint 10
      // rejects outright — the flat configs live under `configs.flat`.
      reactHooks.configs.flat['recommended-latest'],
    ],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // Node-side: config files and the plain-JS token generator. No browser globals, and no
  // type-aware rules — they have no parser services and would hard-error.
  {
    files: ['**/*.{js,mjs,cjs}', '*.config.ts'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Vite/Vitest config files are TypeScript but run in Node.
  {
    files: ['*.config.ts'],
    languageOptions: { globals: globals.node },
  },

  // Tests may reach into internals and assert on non-null values.
  {
    files: ['**/*.test.{ts,tsx}', 'src/test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
)
