/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as CardsKeyRouteImport } from './routes/cards.$key'
import { Route as ProjectsProjectKeyBoardRouteImport } from './routes/projects.$projectKey.board'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsKeyRoute = CardsKeyRouteImport.update({
  id: '/cards/$key',
  path: '/cards/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectKeyBoardRoute = ProjectsProjectKeyBoardRouteImport.update({
  id: '/projects/$projectKey/board',
  path: '/projects/$projectKey/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/cards/$key': typeof CardsKeyRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/cards/$key': typeof CardsKeyRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/styleguide': typeof StyleguideRoute
  '/cards/$key': typeof CardsKeyRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectKey/board': typeof ProjectsProjectKeyBoardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/styleguide'
    | '/cards/$key'
    | '/projects/'
    | '/projects/$projectKey/board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/styleguide'
    | '/cards/$key'
    | '/projects'
    | '/projects/$projectKey/board'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/login'
    | '/styleguide'
    | '/cards/$key'
    | '/projects/'
    | '/projects/$projectKey/board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  StyleguideRoute: typeof StyleguideRoute
  CardsKeyRoute: typeof CardsKeyRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectKeyBoardRoute: typeof ProjectsProjectKeyBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$key': {
      id: '/cards/$key'
      path: '/cards/$key'
      fullPath: '/cards/$key'
      preLoaderRoute: typeof CardsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectKey/board': {
      id: '/projects/$projectKey/board'
      path: '/projects/$projectKey/board'
      fullPath: '/projects/$projectKey/board'
      preLoaderRoute: typeof ProjectsProjectKeyBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  StyleguideRoute: StyleguideRoute,
  CardsKeyRoute: CardsKeyRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectKeyBoardRoute: ProjectsProjectKeyBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
